export type ToolStatus = 'normal' | 'new' | 'hot';

export interface Tool {
  name: string;
  description: string;
  href: string;
  icon: string;
  status: ToolStatus;
}

export interface Category {
  type: string;
  name: string;
  icon: string;
  children: Tool[];
}

export const categories: Category[] = [
  {
    type: 'crypto',
    name: '加密解密',
    icon: 'i-carbon-security',
    children: [
      {
        name: 'Token 生成器',
        description: '生成随机 Token',
        href: '/tools/crypto/token-generator',
        icon: 'i-carbon-key',
        status: 'normal',
      },
      {
        name: '文本哈希',
        description: '生成文本的哈希值 (MD5, SHA1, SHA256 等)',
        href: '/tools/crypto/hash-text',
        icon: 'i-carbon-hash',
        status: 'normal',
      },
      {
        name: 'Bcrypt 加密',
        description: 'Bcrypt 加密和验证',
        href: '/tools/crypto/bcrypt',
        icon: 'i-carbon-password',
        status: 'normal',
      },
      {
        name: 'UUID 生成器',
        description: '生成 UUID',
        href: '/tools/crypto/uuid-generator',
        icon: 'i-carbon-identification',
        status: 'normal',
      },
      {
        name: 'ULID 生成器',
        description: '生成 ULID',
        href: '/tools/crypto/ulid-generator',
        icon: 'i-carbon-identification',
        status: 'normal',
      },
      {
        name: '文本加密解密',
        description: '对称加密解密文本',
        href: '/tools/crypto/encrypt-decrypt',
        icon: 'i-carbon-locked',
        status: 'normal',
      },
      {
        name: 'BIP39 助记词',
        description: '生成 BIP39 助记词',
        href: '/tools/crypto/bip39',
        icon: 'i-carbon-book',
        status: 'normal',
      },
      {
        name: 'HMAC 生成器',
        description: '生成 HMAC',
        href: '/tools/crypto/hmac-generator',
        icon: 'i-carbon-key',
        status: 'normal',
      },
      {
        name: 'RSA 密钥对',
        description: '生成 RSA 密钥对',
        href: '/tools/crypto/rsa-key-pair',
        icon: 'i-carbon-key',
        status: 'normal',
      },
      {
        name: '密码强度分析',
        description: '分析密码强度',
        href: '/tools/crypto/password-strength',
        icon: 'i-carbon-security',
        status: 'normal',
      },
      {
        name: 'PDF 签名检查',
        description: '验证 PDF 数字签名',
        href: '/tools/crypto/pdf-signature-checker',
        icon: 'i-carbon-document-signed',
        status: 'new',
      },
      {
        name: '二维码生成器',
        description: '生成文本/URL 二维码',
        href: '/tools/web/qrcode-generator',
        icon: 'i-carbon-qr-code',
        status: 'new',
      },
      {
        name: 'WiFi 二维码',
        description: '生成 WiFi 连接二维码',
        href: '/tools/web/wifi-qrcode',
        icon: 'i-carbon-wifi',
        status: 'new',
      },
    ],
  },
  {
    type: 'converter',
    name: '转换工具',
    icon: 'i-carbon-data-convert',
    children: [
      {
        name: '日期时间转换',
        description: '日期时间格式转换',
        href: '/tools/converter/date-converter',
        icon: 'i-carbon-time',
        status: 'normal',
      },
      {
        name: '整数进制转换',
        description: '进制转换 (2/8/10/16)',
        href: '/tools/converter/base-converter',
        icon: 'i-carbon-number',
        status: 'normal',
      },
      {
        name: '罗马数字转换',
        description: '阿拉伯数字与罗马数字互转',
        href: '/tools/converter/roman-converter',
        icon: 'i-carbon-text-number-format',
        status: 'normal',
      },
      {
        name: 'Base64 编码解码',
        description: 'Base64 字符串编码解码',
        href: '/tools/converter/base64',
        icon: 'i-carbon-text-kernel',
        status: 'normal',
      },
      {
        name: '颜色转换',
        description: '颜色格式转换 (HEX, RGB, HSL)',
        href: '/tools/converter/color-converter',
        icon: 'i-carbon-color-palette',
        status: 'normal',
      },
      {
        name: '屏幕取色器',
        description: '屏幕取色 + AI 颜色分析',
        href: '/tools/web/color-picker',
        icon: 'i-carbon-color-palette',
        status: 'new',
      },
      {
        name: '大小写转换',
        description: '文本大小写转换',
        href: '/tools/converter/case-converter',
        icon: 'i-carbon-text-capitalize',
        status: 'normal',
      },
      {
        name: 'NATO 字母表',
        description: '文本转 NATO 字母表',
        href: '/tools/text/nato-alphabet',
        icon: 'i-carbon-character-whole',
        status: 'normal',
      },
      {
        name: 'ASCII 二进制',
        description: '文本转 ASCII 二进制',
        href: '/tools/text/text-to-ascii',
        icon: 'i-carbon-data-binary',
        status: 'normal',
      },
      {
        name: 'Unicode 转换',
        description: '文本转 Unicode',
        href: '/tools/text/unicode',
        icon: 'i-carbon-text-kernel',
        status: 'normal',
      },
      {
        name: 'YAML 转 JSON',
        description: 'YAML 转为 JSON',
        href: '/tools/converter/yaml-to-json',
        icon: 'i-carbon-data-structured',
        status: 'normal',
      },
      {
        name: 'JSON 转 YAML',
        description: 'JSON 转为 YAML',
        href: '/tools/converter/json-to-yaml',
        icon: 'i-carbon-data-structured',
        status: 'normal',
      },
      {
        name: 'YAML 转 TOML',
        description: 'YAML 转为 TOML',
        href: '/tools/converter/yaml-to-toml',
        icon: 'i-carbon-document',
        status: 'normal',
      },
      {
        name: 'JSON 转 TOML',
        description: 'JSON 转为 TOML',
        href: '/tools/converter/json-to-toml',
        icon: 'i-carbon-document',
        status: 'normal',
      },
      {
        name: 'TOML 转 JSON',
        description: 'TOML 转为 JSON',
        href: '/tools/converter/toml-to-json',
        icon: 'i-carbon-document',
        status: 'normal',
      },
      {
        name: 'TOML 转 YAML',
        description: 'TOML 转为 YAML',
        href: '/tools/converter/toml-to-yaml',
        icon: 'i-carbon-document',
        status: 'normal',
      },
      {
        name: 'XML 转 JSON',
        description: 'XML 转为 JSON',
        href: '/tools/converter/xml-to-json',
        icon: 'i-carbon-code',
        status: 'normal',
      },
      {
        name: 'JSON 转 XML',
        description: 'JSON 转为 XML',
        href: '/tools/converter/json-to-xml',
        icon: 'i-carbon-code',
        status: 'normal',
      },
      {
        name: 'Markdown 转 HTML',
        description: 'Markdown 转为 HTML',
        href: '/tools/converter/markdown-to-html',
        icon: 'i-carbon-document-markdown',
        status: 'normal',
      },
      {
        name: 'Base64 文件转换',
        description: '文件与 Base64 互转',
        href: '/tools/converter/base64-file',
        icon: 'i-carbon-document-attachment',
        status: 'new',
      },
      {
        name: '列表转换器',
        description: '多种列表格式转换',
        href: '/tools/converter/list-converter',
        icon: 'i-carbon-list-bulleted',
        status: 'new',
      },
      {
        name: '温度转换器',
        description: '摄氏度、华氏度、开尔文转换',
        href: '/tools/converter/temperature-converter',
        icon: 'i-carbon-temperature',
        status: 'new',
      },
      {
        name: 'JSON 转 CSV',
        description: 'JSON 数据转为 CSV 格式',
        href: '/tools/converter/json-to-csv',
        icon: 'i-carbon-csv',
        status: 'new',
      },
      {
        name: '图片压缩',
        description: 'AI 智能图片压缩，支持批量处理和多种格式',
        href: '/tools/ai/image-compressor',
        icon: 'i-carbon-image',
        status: 'new',
      },
    ],
  },
  {
    type: 'web',
    name: 'Web 开发',
    icon: 'i-carbon-code',
    children: [
      {
        name: 'URL 编码解码',
        description: 'URL 编码和解码',
        href: '/tools/web/url-encoder',
        icon: 'i-carbon-link',
        status: 'normal',
      },
      {
        name: 'HTML 实体转义',
        description: 'HTML 实体编码和解码',
        href: '/tools/web/html-escape',
        icon: 'i-carbon-code',
        status: 'normal',
      },
      {
        name: 'URL 解析',
        description: '解析 URL 各部分',
        href: '/tools/web/url-parser',
        icon: 'i-carbon-link',
        status: 'normal',
      },
      {
        name: '设备信息',
        description: '获取当前设备信息',
        href: '/tools/web/device-info',
        icon: 'i-carbon-device-laptop',
        status: 'normal',
      },
      {
        name: 'Basic Auth 生成',
        description: '生成 Basic Auth 头',
        href: '/tools/crypto/basic-auth',
        icon: 'i-carbon-user-avatar',
        status: 'normal',
      },
      {
        name: 'Open Graph 生成',
        description: '生成 Open Graph 元标签',
        href: '/tools/web/open-graph',
        icon: 'i-carbon-share',
        status: 'normal',
      },
      {
        name: 'OTP 验证码',
        description: '生成 TOTP/HOTP 验证码',
        href: '/tools/web/otp-generator',
        icon: 'i-carbon-time',
        status: 'normal',
      },
      {
        name: 'MIME 类型',
        description: '查询 MIME 类型',
        href: '/tools/web/mime-types',
        icon: 'i-carbon-document',
        status: 'normal',
      },
      {
        name: 'JWT 解析',
        description: '解析 JWT Token',
        href: '/tools/web/jwt-parser',
        icon: 'i-carbon-token',
        status: 'normal',
      },
      {
        name: '键码信息',
        description: '查询键码信息',
        href: '/tools/web/keycode',
        icon: 'i-carbon-keyboard',
        status: 'normal',
      },
      {
        name: 'Slug 转换',
        description: '将文本转换为 URL Slug',
        href: '/tools/text/slugify',
        icon: 'i-carbon-text-link',
        status: 'normal',
      },
      {
        name: 'JSON 格式化',
        description: 'JSON 格式化和高亮',
        href: '/tools/converter/json-formatter',
        icon: 'i-carbon-data-structured',
        status: 'normal',
      },
      {
        name: 'HTML WYSIWYG 编辑器',
        description: '可视化 HTML 编辑器',
        href: '/tools/web/html-wysiwyg-editor',
        icon: 'i-carbon-text-annotation-toggle',
        status: 'new',
      },
      {
        name: 'HTTP 状态码',
        description: 'HTTP 状态码速查',
        href: '/tools/web/http-status-codes',
        icon: 'i-carbon-network-4',
        status: 'new',
      },
      {
        name: 'User Agent 解析',
        description: '解析浏览器 UA 信息',
        href: '/tools/web/user-agent-parser',
        icon: 'i-carbon-user-avatar',
        status: 'new',
      },
      {
        name: 'SVG 占位图',
        description: '生成 SVG 占位图片',
        href: '/tools/text/svg-placeholder',
        icon: 'i-carbon-image',
        status: 'new',
      },
    ],
  },
  {
    type: 'cron',
    name: 'Cron 工具',
    icon: 'i-carbon-time',
    children: [
      {
        name: 'Cron 表达式生成',
        description: '可视化生成 Cron 表达式',
        href: '/tools/cron/cron-generator',
        icon: 'i-carbon-time',
        status: 'normal',
      },
      {
        name: 'Cron 表达式解析',
        description: '解析 Cron 表达式',
        href: '/tools/cron/cron-parser',
        icon: 'i-carbon-time',
        status: 'normal',
      },
    ],
  },
  {
    type: 'network',
    name: '网络工具',
    icon: 'i-carbon-network',
    children: [
      {
        name: 'IPv4 地址转换',
        description: 'IPv4 地址在十进制/十六进制/二进制/八进制间转换',
        href: '/tools/network/ipv4-address-converter',
        icon: 'i-carbon-network-4',
        status: 'new',
      },
      {
        name: 'IPv4 范围扩展',
        description: '将 IPv4 地址范围展开为完整地址列表',
        href: '/tools/network/ipv4-range-expander',
        icon: 'i-carbon-network-4',
        status: 'new',
      },
      {
        name: 'IPv6 ULA 生成',
        description: '生成随机的 IPv6 唯一本地地址',
        href: '/tools/network/ipv6-ula-generator',
        icon: 'i-carbon-network-4',
        status: 'new',
      },
      {
        name: 'MAC 地址生成',
        description: '生成随机 MAC 地址，支持自定义格式',
        href: '/tools/network/mac-address-generator',
        icon: 'i-carbon-network-enterprise',
        status: 'new',
      },
      {
        name: 'MAC 地址查询',
        description: '查询 MAC 地址厂商信息',
        href: '/tools/network/mac-address-lookup',
        icon: 'i-carbon-search',
        status: 'new',
      },
      {
        name: 'IPv4 子网计算器',
        description: '计算子网掩码、广播地址等',
        href: '/tools/network/ipv4-subnet-calculator',
        icon: 'i-carbon-subnet',
        status: 'new',
      },
      {
        name: '随机端口生成器',
        description: '生成随机可用端口号',
        href: '/tools/network/random-port-generator',
        icon: 'i-carbon-port',
        status: 'new',
      },
      {
        name: 'Outlook 安全链接解码',
        description: '解码 Outlook 安全链接',
        href: '/tools/web/outlook-safelink',
        icon: 'i-carbon-link',
        status: 'new',
      },
    ],
  },
  {
    type: 'math',
    name: '数学计算',
    icon: 'i-carbon-calculator',
    children: [
      {
        name: '数学表达式计算器',
        description: '支持三角函数、对数等数学表达式求值',
        href: '/tools/math/math-evaluator',
        icon: 'i-carbon-calculator',
        status: 'new',
      },
      {
        name: 'ETA 预计时间',
        description: '根据当前进度预估任务完成时间',
        href: '/tools/math/eta-calculator',
        icon: 'i-carbon-time',
        status: 'new',
      },
      {
        name: '百分比计算器',
        description: '多种百分比计算模式',
        href: '/tools/math/percentage-calculator',
        icon: 'i-carbon-percentage',
        status: 'new',
      },
      {
        name: '秒表 / 计时器',
        description: '高精度秒表，支持分圈计时',
        href: '/tools/math/chronometer',
        icon: 'i-carbon-timer',
        status: 'new',
      },
    ],
  },
  {
    type: 'text',
    name: '文本工具',
    icon: 'i-carbon-text-align-left',
    children: [
      {
        name: '文本统计',
        description: '统计字数、字符数、行数、段落数',
        href: '/tools/text/text-statistics',
        icon: 'i-carbon-text-mining',
        status: 'new',
      },
      {
        name: '字符串混淆',
        description: '多种方式混淆字符串',
        href: '/tools/text/string-obfuscator',
        icon: 'i-carbon-text-tracking',
        status: 'new',
      },
      {
        name: 'ASCII 艺术生成',
        description: '生成 ASCII 艺术字',
        href: '/tools/text/ascii-art-generator',
        icon: 'i-carbon-text-font',
        status: 'new',
      },
      {
        name: 'Emoji 选择器',
        description: '浏览和复制 Emoji 表情',
        href: '/tools/text/emoji-picker',
        icon: 'i-carbon-face-wink',
        status: 'new',
      },
      {
        name: '文本对比',
        description: '对比两段文本的差异',
        href: '/tools/text/text-diff',
        icon: 'i-carbon-compare',
        status: 'new',
      },
      {
        name: '邮箱规范化',
        description: '规范化邮箱地址格式',
        href: '/tools/web/email-normalizer',
        icon: 'i-carbon-email',
        status: 'new',
      },
      {
        name: '手机号解析',
        description: '解析和验证手机号',
        href: '/tools/web/phone-parser',
        icon: 'i-carbon-phone',
        status: 'new',
      },
      {
        name: '数字缩写生成',
        description: '生成数字缩写（如 i18n）',
        href: '/tools/text/numeronym-generator',
        icon: 'i-carbon-text-small-caps',
        status: 'new',
      },
      {
        name: 'Lorem Ipsum',
        description: '生成占位文本',
        href: '/tools/text/lorem-ipsum',
        icon: 'i-carbon-text-fill',
        status: 'new',
      },
    ],
  },
  {
    type: 'dev',
    name: '开发工具',
    icon: 'i-carbon-code',
    children: [
      {
        name: 'SQL 格式化',
        description: 'SQL 语句格式化',
        href: '/tools/dev/sql-formatter',
        icon: 'i-carbon-sql',
        status: 'new',
      },
      {
        name: 'XML 格式化',
        description: 'XML 格式化和高亮',
        href: '/tools/dev/xml-formatter',
        icon: 'i-carbon-code',
        status: 'new',
      },
      {
        name: 'YAML 格式化',
        description: 'YAML 格式化和高亮',
        href: '/tools/dev/yaml-formatter',
        icon: 'i-carbon-code',
        status: 'new',
      },
      {
        name: 'JSON 压缩',
        description: '压缩 JSON 去除空白',
        href: '/tools/converter/json-minify',
        icon: 'i-carbon-minimize',
        status: 'new',
      },
      {
        name: 'JSON 对比',
        description: '对比两个 JSON 的差异',
        href: '/tools/dev/json-diff',
        icon: 'i-carbon-compare',
        status: 'new',
      },
      {
        name: '正则表达式测试',
        description: '测试和调试正则表达式',
        href: '/tools/text/regex-tester',
        icon: 'i-carbon-regex',
        status: 'new',
      },
      {
        name: '正则表达式速查',
        description: '常用正则表达式参考',
        href: '/tools/text/regex-cheatsheet',
        icon: 'i-carbon-notebook-reference',
        status: 'new',
      },
      {
        name: 'Chmod 计算器',
        description: '计算 Linux 文件权限',
        href: '/tools/math/chmod-calculator',
        icon: 'i-carbon-terminal',
        status: 'new',
      },
      {
        name: 'Git 速查表',
        description: '常用 Git 命令参考',
        href: '/tools/dev/git-cheatsheet',
        icon: 'i-carbon-branch',
        status: 'new',
      },
      {
        name: 'Docker Compose 生成',
        description: '生成 Docker Compose 配置',
        href: '/tools/network/docker-compose-generator',
        icon: 'i-carbon-container-software',
        status: 'new',
      },
      {
        name: '性能基准测试',
        description: '代码性能基准测试',
        href: '/tools/math/benchmark-builder',
        icon: 'i-carbon-meter',
        status: 'new',
      },
    ],
  },
  {
    type: 'validator',
    name: '验证工具',
    icon: 'i-carbon-checkmark',
    children: [
      {
        name: 'IBAN 验证',
        description: '验证 IBAN 账号格式',
        href: '/tools/validator/iban-validator',
        icon: 'i-carbon-bank',
        status: 'new',
      },
    ],
  },
  {
    type: 'ai',
    name: 'AI 工具',
    icon: 'i-carbon-machine-learning',
    children: [
      {
        name: 'AI 提示词优化',
        description: '优化 AI 提示词',
        href: '/tools/ai/ai-prompt-optimizer',
        icon: 'i-carbon-ai',
        status: 'hot',
      },
      {
        name: '提示词',
        description: 'AI 提示词库',
        href: '/prompts',
        icon: 'i-carbon-chat',
        status: 'normal',
      },
      {
        name: 'Skills',
        description: 'AI Skills 库',
        href: '/skills',
        icon: 'i-carbon-tool-kit',
        status: 'normal',
      },
      {
        name: 'Rules',
        description: 'AI Rules 库',
        href: '/rules',
        icon: 'i-carbon-rule',
        status: 'normal',
      },
    ],
  },
  {
    type: 'life',
    name: '生活工具',
    icon: 'i-carbon-home',
    children: [
      {
        name: '故事会',
        description: '儿童故事浏览、搜索、AI朗读、续写、总结',
        href: '/tools/life/story-collection',
        icon: 'i-carbon-book',
        status: 'new',
      },
      {
        name: '历史上的今天',
        description: '查看历史上今天发生的重要事件，AI智能解读',
        href: '/tools/life/today-in-history',
        icon: 'i-carbon-events',
        status: 'new',
      },
      {
        name: '万年历',
        description: '公历农历对照、节假日查询、宜忌信息',
        href: '/tools/life/calendar',
        icon: 'i-carbon-calendar',
        status: 'new',
      },
    ],
  },
];

export const toolModules = [
  {
    type: 'prompts',
    name: '提示词',
    icon: 'i-carbon-chat',
    href: '/prompts',
  },
  {
    type: 'skills',
    name: 'Skills',
    icon: 'i-carbon-tool-kit',
    href: '/skills',
  },
  {
    type: 'rules',
    name: 'Rules',
    icon: 'i-carbon-rule',
    href: '/rules',
  },
];
