name: github pages
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 获取源码
        uses: actions/checkout@v4

      - name: Node环境版本
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: 安装pnpm
        with:
          version: 9
          run_install: false

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 打包
        run: pnpm run build && touch ./out/.nojekyll

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean: true
